{"name": "test_SignUp_with_invalid_otp[chrome]", "status": "passed", "attachments": [{"name": "log", "source": "234d792a-1be9-47f6-a3c7-1f729d534cac-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_browser", "value": "'chrome'"}], "start": 1696849112772, "stop": 1696849124466, "uuid": "1d5ae8db-19ff-4c16-a950-397ce7fbacad", "historyId": "f4d7d1056a5b1730cc61ce15b1742450", "testCaseId": "4f772473654fef98a318695f996e8649", "fullName": "test_SSO.Test_SSO#test_SignUp_with_invalid_otp", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('log_on_failure', 'get_browser')"}, {"name": "suite", "value": "test_SSO"}, {"name": "subSuite", "value": "Test_SSO"}, {"name": "host", "value": "CYREX-x-CYREX"}, {"name": "thread", "value": "10232-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_SSO"}]}